// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApiRZHD.Models;

public partial class Passport_datum
{
    public int Id { get; set; }

    public string Login { get; set; }

    public string Passport_series { get; set; }

    public string Passport_number { get; set; }

    public string First_name { get; set; }

    public string Last_name { get; set; }

    public string Middle_name { get; set; }

    [JsonIgnore]
    public virtual User LoginNavigation { get; set; }
}