// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebApiRZHD.Models;

public partial class RZHDContext : DbContext
{
    public RZHDContext()
    {
    }

    public RZHDContext(DbContextOptions<RZHDContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Passport_datum> Passport_data { get; set; }

    public virtual DbSet<Schedule> Schedules { get; set; }

    public virtual DbSet<Station> Stations { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<User_Schedule> User_Schedules { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) => optionsBuilder.UseLazyLoadingProxies().UseSqlServer("Data Source=DESKTOP-2N8HAGP\\SQLEXPRESS;Initial Catalog=RZHD;Integrated Security=True;TrustServerCertificate=True;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Passport_datum>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Passport__3214EC0750E81F94");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.First_name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Last_name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Login).HasMaxLength(100);
            entity.Property(e => e.Middle_name).HasMaxLength(100);
            entity.Property(e => e.Passport_number)
                .IsRequired()
                .HasMaxLength(6);
            entity.Property(e => e.Passport_series)
                .IsRequired()
                .HasMaxLength(4);

            entity.HasOne(d => d.LoginNavigation).WithMany(p => p.Passport_data)
                .HasForeignKey(d => d.Login)
                .HasConstraintName("FK__Passport___Login__5EBF139D");
        });

        modelBuilder.Entity<Schedule>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Schedule__3214EC07178C0F3D");

            entity.ToTable("Schedule");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Arrival_date_time).HasColumnType("datetime");
            entity.Property(e => e.Departure_date_time).HasColumnType("datetime");
            entity.Property(e => e.Ticket_price).HasColumnType("money");

            entity.HasOne(d => d.Arrival_stationNavigation).WithMany(p => p.ScheduleArrival_stationNavigations)
                .HasForeignKey(d => d.Arrival_station)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Schedule__Arriva__6477ECF3");

            entity.HasOne(d => d.Departure_stationNavigation).WithMany(p => p.ScheduleDeparture_stationNavigations)
                .HasForeignKey(d => d.Departure_station)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Schedule__Depart__6383C8BA");
        });

        modelBuilder.Entity<Station>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Station__3214EC0748F2AEF5");

            entity.ToTable("Station");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Login).HasName("PK__User__5E55825A128CCC93");

            entity.ToTable("User");

            entity.Property(e => e.Login).HasMaxLength(100);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Role)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<User_Schedule>(entity =>
        {
            entity.HasKey(e => new { e.Login_user, e.Id_schedule }).HasName("PK__User_Sch__4AC1AE849B30FA6D");

            entity.ToTable("User_Schedule");

            entity.Property(e => e.Login_user).HasMaxLength(100);

            entity.HasOne(d => d.Id_scheduleNavigation).WithMany(p => p.User_Schedules)
                .HasForeignKey(d => d.Id_schedule)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__User_Sche__Id_sc__68487DD7");

            entity.HasOne(d => d.Login_userNavigation).WithMany(p => p.User_Schedules)
                .HasForeignKey(d => d.Login_user)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__User_Sche__Login__6754599E");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}