// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApiRZHD.Models;

public partial class Schedule
{
    public int Id { get; set; }

    public int Departure_station { get; set; }

    public int Arrival_station { get; set; }

    public DateTime Departure_date_time { get; set; }

    public DateTime Arrival_date_time { get; set; }

    public int Number_of_available_seats { get; set; }

    public decimal Ticket_price { get; set; }

    [JsonIgnore]
    public virtual Station Arrival_stationNavigation { get; set; }

    [JsonIgnore]
    public virtual Station Departure_stationNavigation { get; set; }

    [JsonIgnore]
    public virtual ICollection<User_Schedule> User_Schedules { get; set; } = new List<User_Schedule>();
}