// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApiRZHD.Models;

public partial class Station
{
    public int Id { get; set; }

    public string Name { get; set; }
    
    [JsonIgnore]
    public virtual ICollection<Schedule> ScheduleArrival_stationNavigations { get; set; } = new List<Schedule>();

    [JsonIgnore]
    public virtual ICollection<Schedule> ScheduleDeparture_stationNavigations { get; set; } = new List<Schedule>();
}