// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApiRZHD.Models;

public partial class User
{
    public string Login { get; set; }

    public string Password { get; set; }

    public string Role { get; set; }

    [JsonIgnore]
    public virtual ICollection<Passport_datum> Passport_data { get; set; } = new List<Passport_datum>();

    [JsonIgnore]
    public virtual ICollection<User_Schedule> User_Schedules { get; set; } = new List<User_Schedule>();
}