// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.Text.Json.Serialization;
using System;
using System.Collections.Generic;

namespace WebApiRZHD.Models;

public partial class User_Schedule
{
    public string Login_user { get; set; }

    public int Id_schedule { get; set; }

    public DateOnly Date_of_purchase { get; set; }

    [JsonIgnore]
    public virtual Schedule Id_scheduleNavigation { get; set; }

    [JsonIgnore]
    public virtual User Login_userNavigation { get; set; }
}